# Building LOCAL Docker Image and integrating SBC scripts
# this one adjusts for the test for yourstreamlive service

FROM 		nachochip/ffmpeg:stable

MAINTAINER 	Nachochip 	<blockchaincolony@gmail.com>

ADD		0*		/usr/local/bin/

CMD           	["05-yourstreamlive.sh"]
ENTRYPOINT 	["bash"]
